language: python
python:
  - "3.8"

install:
  - pip install pipenv --upgrade-strategy=only-if-needed
  - pipenv install --dev
# command to run tests
script:
  - pytest --create-db -m "not smoke_test" -m "not dramatiq"
  - make ci
services:
  - mysql
  - rabbitmq
  - redis-server
after_success:
  - codecov
