---
- name: Test out running ansible from actions
  hosts:
    - all
  remote_user: "deploy"
  become: no

  tasks:
    - name: run a sample command as a test
      command: echo "Accesing TOP_SEKRET via ansible env lookup - {{ lookup('env','TOP_SEKRET') }}"
      register: result
      args:
        chdir: /home/deploy

    - name: test accessing values added to the environment from github secrets for a specific environment
      ansible.builtin.debug:
        var: result
